### ISSUE TITLE
希望能做个susudm.com的云插件

### ISSUE THREAD

**Issue by lon91ong** [artxia/FreedTV#1]
我这里的网络环境中，多番体验下来就数这个网站的速度好用，备用线路也多
自己做了网址播放：
```
    {
      "name": "速速影视(网址播放)",
      "pic": "https://img9.doubanio.com/view/activity_page/raw/public/p2446.jpg",
      "ads": "",
      "webUrl": "http://www.susudm.com",
      "webOpen": true,
      "click": true
    },
```
可以播放，但是体验上不及解析网页后的效果
自己试着“照猫画虎”，直接就卡在了**导航**页面的解析上，这个网站没有把全部的资源归类到统一的页面，而是直接在首页划分了“电视剧”，“电影”，“动漫”，“综艺”几类，然后各自做的导航页，翻了几个现有的例子，没找到类似划分的
希望大侠出手帮忙

**Comment by artxia** [comment]
这个需要花时间调试，我目前没精力搞
建议直接找原作者或者自己慢慢试

**Comment by lon91ong** [comment]
@artxia 原作者的项目地址在哪里? 没加过微信公众号

**Comment by artxia** [comment]
> @artxia 原作者的项目地址在哪里? 没加过微信公众号

貌似只有公众号留言
